# This is all static provisioning
# this is PV (Persistent Volumes)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce #EBS volume should have readwriteonce, because it Hard disk (HD)
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-005884f1b6510a38f
---
# this is PVC (Persistent Volumes Claim)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set. for static provisioning this is empty
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
# This is pod
apiVersion: v1
kind: Pod
metadata:
  name: app
  Labels:
    demo: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1b
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-static
---
# This is Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: ebs-static
  Labels:
    demo: ebs-static
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port