apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
---
# This is pod
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    demo: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  nodeSelector:
    zone: 1b
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
# This is Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    demo: ebs-static
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port