apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
# list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["slepp","300  "]
  - name: 