apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    coures: DevOps
    trainer: "Sivakumar"
spec:
# list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80